name: TownyFly
description: Allow players to fly within their own (or others) towns.
version: 4
author: DrDoof
main: net.josef.townyfly.TownyFly
depend: [Towny]

permissions:
  townyfly.toggle.self:
    description: Permission to use the /tfly command.
  townyfly.toggle.others:
    description: Permission to use the /tfly <player> command.
  townyfly.othertown:
    description: Permission to tfly in a town where the player is not a resident in.

commands:
  townyfly:
    description: Toggle flying in towns.
    aliases: [tfly]
    usage: /townyfly <player>
    permission: townyfly.toggle.self
    permission-message: You do not have permission to use this command.